# Generated by Django 3.0.8 on 2020-08-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceneed',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
