# Generated by Django 3.0.8 on 2020-08-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_post_pst'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image2',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image3',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
    ]
