# Generated by Django 3.0.8 on 2020-08-15 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200813_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotegories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='auther',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Cotegories'),
            preserve_default=False,
        ),
    ]
