# Generated by Django 3.0.8 on 2020-08-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200816_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auther',
        ),
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
